[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64"]

[dependencies]
prefect = "==3.4.6"
tiled-client = ">0.1.b035"
prefect-docker = "*"
databroker = "*"
pandas = "*"
event-model = "*"
tqdm = "*"
